services:

  # Garnet is a new remote cache-store from Microsoft Research - https://github.com/microsoft/garnet
  garnet:
    image: 'ghcr.io/microsoft/garnet'
    container_name: ai-devs-garnet
    restart: always
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - ai-devs-garnet_data:/data
    command: [ "--lua=True"]

  # Qdrant is a vector search engine - https://qdrant.tech/
  qdrant:
    image: qdrant/qdrant:latest
    container_name: ai-devs-qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ai-devs-qdrant_data:/qdrant/storage

  # Postgres is a relational database - https://www.postgresql.org/
  postgres:
    image: postgres:16.1-alpine
    container_name: ai-devs-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ai-devs-postgres_data:/var/lib/postgresql/data

  # Neo4j is a graph database - https://neo4j.com/
  neo4j:
    image: neo4j:latest
    container_name: ai-devs-neo4j
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ai-devs-neo4j_data:/data
      - ai-devs-neo4j_logs:/logs
      - ai-devs-neo4j_config:/config
      - ai-devs-neo4j_plugins:/plugins
    restart: always


volumes:
  ai-devs-garnet_data:
  ai-devs-postgres_data:
  ai-devs-qdrant_data:
  ai-devs-neo4j_data:
  ai-devs-neo4j_logs:
  ai-devs-neo4j_config:
  ai-devs-neo4j_plugins:
